# SIT 环境（开发自测）
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pengyouquan_english_sit?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: pengyouquan123
