# SIT 环境（开发自测）
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${SPRING_DATASOURCE_HOST:mysql}:3306/${SPRING_DATASOURCE_DB:pengyouquan_english}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:pengyouquan123}
